# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common_msgs/map_msgs/map_pnc_junction.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'common_msgs/map_msgs/map_pnc_junction.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common_msgs.map_msgs import map_geometry_pb2 as common__msgs_dot_map__msgs_dot_map__geometry__pb2
from common_msgs.map_msgs import map_id_pb2 as common__msgs_dot_map__msgs_dot_map__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+common_msgs/map_msgs/map_pnc_junction.proto\x12\x10map_engine.hdmap\x1a\'common_msgs/map_msgs/map_geometry.proto\x1a!common_msgs/map_msgs/map_id.proto\"\xaa\x02\n\x07Passage\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.map_engine.hdmap.Id\x12\'\n\tsignal_id\x18\x02 \x03(\x0b\x32\x14.map_engine.hdmap.Id\x12&\n\x08yield_id\x18\x03 \x03(\x0b\x32\x14.map_engine.hdmap.Id\x12*\n\x0cstop_sign_id\x18\x04 \x03(\x0b\x32\x14.map_engine.hdmap.Id\x12%\n\x07lane_id\x18\x05 \x03(\x0b\x32\x14.map_engine.hdmap.Id\x12,\n\x04type\x18\x06 \x01(\x0e\x32\x1e.map_engine.hdmap.Passage.Type\"+\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0c\n\x08\x45NTRANCE\x10\x01\x12\x08\n\x04\x45XIT\x10\x02\"\\\n\x0cPassageGroup\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.map_engine.hdmap.Id\x12*\n\x07passage\x18\x02 \x03(\x0b\x32\x19.map_engine.hdmap.Passage\"\xbc\x01\n\x0bPNCJunction\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.map_engine.hdmap.Id\x12*\n\x07polygon\x18\x02 \x01(\x0b\x32\x19.map_engine.hdmap.Polygon\x12(\n\noverlap_id\x18\x03 \x03(\x0b\x32\x14.map_engine.hdmap.Id\x12\x35\n\rpassage_group\x18\x04 \x03(\x0b\x32\x1e.map_engine.hdmap.PassageGroup')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_msgs.map_msgs.map_pnc_junction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PASSAGE']._serialized_start=142
  _globals['_PASSAGE']._serialized_end=440
  _globals['_PASSAGE_TYPE']._serialized_start=397
  _globals['_PASSAGE_TYPE']._serialized_end=440
  _globals['_PASSAGEGROUP']._serialized_start=442
  _globals['_PASSAGEGROUP']._serialized_end=534
  _globals['_PNCJUNCTION']._serialized_start=537
  _globals['_PNCJUNCTION']._serialized_end=725
# @@protoc_insertion_point(module_scope)
