# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common_msgs/map_msgs/map_speed_control.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'common_msgs/map_msgs/map_speed_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common_msgs.map_msgs import map_geometry_pb2 as common__msgs_dot_map__msgs_dot_map__geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,common_msgs/map_msgs/map_speed_control.proto\x12\x10map_engine.hdmap\x1a\'common_msgs/map_msgs/map_geometry.proto\"]\n\x0cSpeedControl\x12\x0c\n\x04name\x18\x01 \x01(\t\x12*\n\x07polygon\x18\x02 \x01(\x0b\x32\x19.map_engine.hdmap.Polygon\x12\x13\n\x0bspeed_limit\x18\x03 \x01(\x01\"F\n\rSpeedControls\x12\x35\n\rspeed_control\x18\x01 \x03(\x0b\x32\x1e.map_engine.hdmap.SpeedControl')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_msgs.map_msgs.map_speed_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPEEDCONTROL']._serialized_start=107
  _globals['_SPEEDCONTROL']._serialized_end=200
  _globals['_SPEEDCONTROLS']._serialized_start=202
  _globals['_SPEEDCONTROLS']._serialized_end=272
# @@protoc_insertion_point(module_scope)
