# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common_msgs/map_msgs/map_barrier_gate.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'common_msgs/map_msgs/map_barrier_gate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common_msgs.map_msgs import map_geometry_pb2 as common__msgs_dot_map__msgs_dot_map__geometry__pb2
from common_msgs.map_msgs import map_id_pb2 as common__msgs_dot_map__msgs_dot_map__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+common_msgs/map_msgs/map_barrier_gate.proto\x12\x10map_engine.hdmap\x1a\'common_msgs/map_msgs/map_geometry.proto\x1a!common_msgs/map_msgs/map_id.proto\"\xc1\x02\n\x0b\x42\x61rrierGate\x12 \n\x02id\x18\x01 \x02(\x0b\x32\x14.map_engine.hdmap.Id\x12;\n\x04type\x18\x02 \x01(\x0e\x32-.map_engine.hdmap.BarrierGate.BarrierGateType\x12*\n\x07polygon\x18\x03 \x01(\x0b\x32\x19.map_engine.hdmap.Polygon\x12*\n\tstop_line\x18\x04 \x03(\x0b\x32\x17.map_engine.hdmap.Curve\x12(\n\noverlap_id\x18\x05 \x03(\x0b\x32\x14.map_engine.hdmap.Id\"Q\n\x0f\x42\x61rrierGateType\x12\x07\n\x03ROD\x10\x01\x12\t\n\x05\x46\x45NCE\x10\x02\x12\x0f\n\x0b\x41\x44VERTISING\x10\x03\x12\x0e\n\nTELESCOPIC\x10\x04\x12\t\n\x05OTHER\x10\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_msgs.map_msgs.map_barrier_gate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BARRIERGATE']._serialized_start=142
  _globals['_BARRIERGATE']._serialized_end=463
  _globals['_BARRIERGATE_BARRIERGATETYPE']._serialized_start=382
  _globals['_BARRIERGATE_BARRIERGATETYPE']._serialized_end=463
# @@protoc_insertion_point(module_scope)
