# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common_msgs/map_msgs/map_area.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'common_msgs/map_msgs/map_area.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common_msgs.map_msgs import map_geometry_pb2 as common__msgs_dot_map__msgs_dot_map__geometry__pb2
from common_msgs.map_msgs import map_id_pb2 as common__msgs_dot_map__msgs_dot_map__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#common_msgs/map_msgs/map_area.proto\x12\x10map_engine.hdmap\x1a\'common_msgs/map_msgs/map_geometry.proto\x1a!common_msgs/map_msgs/map_id.proto\"\x85\x03\n\x04\x41rea\x12 \n\x02id\x18\x01 \x02(\x0b\x32\x14.map_engine.hdmap.Id\x12)\n\x04type\x18\x02 \x01(\x0e\x32\x1b.map_engine.hdmap.Area.Type\x12*\n\x07polygon\x18\x03 \x02(\x0b\x32\x19.map_engine.hdmap.Polygon\x12(\n\noverlap_id\x18\x04 \x03(\x0b\x32\x14.map_engine.hdmap.Id\x12\x0c\n\x04name\x18\x05 \x01(\t\"\xcb\x01\n\x04Type\x12\x17\n\x13SHOVEL_LOADING_AREA\x10\x01\x12\x14\n\x10\x43RUSHING_STATION\x10\x02\x12\x11\n\rDISPOSAL_AREA\x10\x03\x12\x10\n\x0cPARKING_AREA\x10\x04\x12\x0f\n\x0bGAS_STATION\x10\x05\x12\x14\n\x10MAINTENANCE_AREA\x10\x06\x12\r\n\tJOP_POINT\x10\x07\x12\x11\n\rPARKING_SPACE\x10\x08\x12\x13\n\x0f\x46REE_SPACE_AREA\x10\t\x12\x11\n\rOBSTACLE_AREA\x10\n')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_msgs.map_msgs.map_area_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AREA']._serialized_start=134
  _globals['_AREA']._serialized_end=523
  _globals['_AREA_TYPE']._serialized_start=320
  _globals['_AREA_TYPE']._serialized_end=523
# @@protoc_insertion_point(module_scope)
