# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common_msgs/map_msgs/map_yield_sign.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'common_msgs/map_msgs/map_yield_sign.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common_msgs.map_msgs import map_geometry_pb2 as common__msgs_dot_map__msgs_dot_map__geometry__pb2
from common_msgs.map_msgs import map_id_pb2 as common__msgs_dot_map__msgs_dot_map__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)common_msgs/map_msgs/map_yield_sign.proto\x12\x10map_engine.hdmap\x1a\'common_msgs/map_msgs/map_geometry.proto\x1a!common_msgs/map_msgs/map_id.proto\"\x83\x01\n\tYieldSign\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.map_engine.hdmap.Id\x12*\n\tstop_line\x18\x02 \x03(\x0b\x32\x17.map_engine.hdmap.Curve\x12(\n\noverlap_id\x18\x03 \x03(\x0b\x32\x14.map_engine.hdmap.Id')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_msgs.map_msgs.map_yield_sign_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_YIELDSIGN']._serialized_start=140
  _globals['_YIELDSIGN']._serialized_end=271
# @@protoc_insertion_point(module_scope)
