# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common_msgs/map_msgs/map_geometry.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'common_msgs/map_msgs/map_geometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common_msgs.basic_msgs import geometry_pb2 as common__msgs_dot_basic__msgs_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'common_msgs/map_msgs/map_geometry.proto\x12\x10map_engine.hdmap\x1a%common_msgs/basic_msgs/geometry.proto\"5\n\x07Polygon\x12*\n\x05point\x18\x01 \x03(\x0b\x32\x1b.map_engine.common.PointENU\"9\n\x0bLineSegment\x12*\n\x05point\x18\x01 \x03(\x0b\x32\x1b.map_engine.common.PointENU\"\xb4\x01\n\x0c\x43urveSegment\x12\x35\n\x0cline_segment\x18\x01 \x01(\x0b\x32\x1d.map_engine.hdmap.LineSegmentH\x00\x12\t\n\x01s\x18\x06 \x01(\x01\x12\x33\n\x0estart_position\x18\x07 \x01(\x0b\x32\x1b.map_engine.common.PointENU\x12\x0f\n\x07heading\x18\x08 \x01(\x01\x12\x0e\n\x06length\x18\t \x01(\x01\x42\x0c\n\ncurve_type\"8\n\x05\x43urve\x12/\n\x07segment\x18\x01 \x03(\x0b\x32\x1e.map_engine.hdmap.CurveSegment')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_msgs.map_msgs.map_geometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POLYGON']._serialized_start=100
  _globals['_POLYGON']._serialized_end=153
  _globals['_LINESEGMENT']._serialized_start=155
  _globals['_LINESEGMENT']._serialized_end=212
  _globals['_CURVESEGMENT']._serialized_start=215
  _globals['_CURVESEGMENT']._serialized_end=395
  _globals['_CURVE']._serialized_start=397
  _globals['_CURVE']._serialized_end=453
# @@protoc_insertion_point(module_scope)
