# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common_msgs/map_msgs/map_signal.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'common_msgs/map_msgs/map_signal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common_msgs.basic_msgs import geometry_pb2 as common__msgs_dot_basic__msgs_dot_geometry__pb2
from common_msgs.map_msgs import map_geometry_pb2 as common__msgs_dot_map__msgs_dot_map__geometry__pb2
from common_msgs.map_msgs import map_id_pb2 as common__msgs_dot_map__msgs_dot_map__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%common_msgs/map_msgs/map_signal.proto\x12\x10map_engine.hdmap\x1a%common_msgs/basic_msgs/geometry.proto\x1a\'common_msgs/map_msgs/map_geometry.proto\x1a!common_msgs/map_msgs/map_id.proto\"\xad\x02\n\tSubsignal\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.map_engine.hdmap.Id\x12.\n\x04type\x18\x02 \x01(\x0e\x32 .map_engine.hdmap.Subsignal.Type\x12-\n\x08location\x18\x03 \x01(\x0b\x32\x1b.map_engine.common.PointENU\"\x9e\x01\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x01\x12\n\n\x06\x43IRCLE\x10\x02\x12\x0e\n\nARROW_LEFT\x10\x03\x12\x11\n\rARROW_FORWARD\x10\x04\x12\x0f\n\x0b\x41RROW_RIGHT\x10\x05\x12\x1a\n\x16\x41RROW_LEFT_AND_FORWARD\x10\x06\x12\x1b\n\x17\x41RROW_RIGHT_AND_FORWARD\x10\x07\x12\x10\n\x0c\x41RROW_U_TURN\x10\x08\"e\n\x08SignInfo\x12-\n\x04type\x18\x01 \x01(\x0e\x32\x1f.map_engine.hdmap.SignInfo.Type\"*\n\x04Type\x12\x08\n\x04None\x10\x00\x12\x18\n\x14NO_RIGHT_TURN_ON_RED\x10\x01\"\xae\x03\n\x06Signal\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.map_engine.hdmap.Id\x12+\n\x08\x62oundary\x18\x02 \x01(\x0b\x32\x19.map_engine.hdmap.Polygon\x12.\n\tsubsignal\x18\x03 \x03(\x0b\x32\x1b.map_engine.hdmap.Subsignal\x12(\n\noverlap_id\x18\x04 \x03(\x0b\x32\x14.map_engine.hdmap.Id\x12+\n\x04type\x18\x05 \x01(\x0e\x32\x1d.map_engine.hdmap.Signal.Type\x12*\n\tstop_line\x18\x06 \x03(\x0b\x32\x17.map_engine.hdmap.Curve\x12-\n\tsign_info\x18\x07 \x03(\x0b\x32\x1a.map_engine.hdmap.SignInfo\"s\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x14\n\x10MIX_2_HORIZONTAL\x10\x02\x12\x12\n\x0eMIX_2_VERTICAL\x10\x03\x12\x14\n\x10MIX_3_HORIZONTAL\x10\x04\x12\x12\n\x0eMIX_3_VERTICAL\x10\x05\x12\n\n\x06SINGLE\x10\x06')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_msgs.map_msgs.map_signal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSIGNAL']._serialized_start=175
  _globals['_SUBSIGNAL']._serialized_end=476
  _globals['_SUBSIGNAL_TYPE']._serialized_start=318
  _globals['_SUBSIGNAL_TYPE']._serialized_end=476
  _globals['_SIGNINFO']._serialized_start=478
  _globals['_SIGNINFO']._serialized_end=579
  _globals['_SIGNINFO_TYPE']._serialized_start=537
  _globals['_SIGNINFO_TYPE']._serialized_end=579
  _globals['_SIGNAL']._serialized_start=582
  _globals['_SIGNAL']._serialized_end=1012
  _globals['_SIGNAL_TYPE']._serialized_start=897
  _globals['_SIGNAL_TYPE']._serialized_end=1012
# @@protoc_insertion_point(module_scope)
