# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common_msgs/map_msgs/map_dynamic.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'common_msgs/map_msgs/map_dynamic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&common_msgs/map_msgs/map_dynamic.proto\x12\x10map_engine.hdmap\"8\n\x08GeoPoint\x12\x0e\n\x01x\x18\x01 \x01(\x01:\x03nan\x12\x0e\n\x01y\x18\x02 \x01(\x01:\x03nan\x12\x0c\n\x01z\x18\x03 \x01(\x01:\x01\x30\"\xd4\x04\n\x0b\x44ynamicData\x12\n\n\x02id\x18\x01 \x02(\t\x12\x30\n\x04type\x18\x02 \x01(\x0e\x32\".map_engine.hdmap.DynamicData.Type\x12\x37\n\x08geo_type\x18\x03 \x01(\x0e\x32%.map_engine.hdmap.DynamicData.GeoType\x12\'\n\x03pts\x18\x04 \x03(\x0b\x32\x1a.map_engine.hdmap.GeoPoint\x12:\n\x03reg\x18\x05 \x01(\x0e\x32-.map_engine.hdmap.DynamicData.BelongingRegion\x12\x0c\n\x04info\x18\x06 \x01(\t\"\x99\x01\n\x04Type\x12\x0e\n\nENTRY_LINE\x10\x01\x12\r\n\tBACK_LINE\x10\x02\x12\r\n\tEXIT_LINE\x10\x03\x12\x14\n\x10\x42\x41\x43K_START_POINT\x10\x04\x12\x12\n\x0e\x42\x41\x43K_END_POINT\x10\x05\x12\x10\n\x0c\x42OILING_AREA\x10\x06\x12\x13\n\x0fIMPASSABLE_AREA\x10\x07\x12\x12\n\x0eSCATTERED_AREA\x10\x08\"S\n\x07GeoType\x12\x0c\n\x08GEO_NONE\x10\x01\x12\r\n\tGEO_POINT\x10\x02\x12\x0c\n\x08GEO_LINE\x10\x03\x12\x0f\n\x0bGEO_POLYGON\x10\x04\x12\x0c\n\x08GEO_POSE\x10\x05\"j\n\x0f\x42\x65longingRegion\x12\n\n\x06UNKNOW\x10\x01\x12\x0e\n\nMAIN_ROASD\x10\x02\x12\x12\n\x0eSHOVEL_LOADING\x10\x03\x12\x14\n\x10\x43RUSHING_STATION\x10\x04\x12\x11\n\rDISPOSAL_AREA\x10\x05\"\x81\x01\n\x07\x44ynamic\x12\x13\n\x0breport_time\x18\x01 \x01(\t\x12\x33\n\x0c\x64ynamic_data\x18\x02 \x03(\x0b\x32\x1d.map_engine.hdmap.DynamicData\x12,\n$lowest_supported_static_data_verison\x18\x03 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_msgs.map_msgs.map_dynamic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEOPOINT']._serialized_start=60
  _globals['_GEOPOINT']._serialized_end=116
  _globals['_DYNAMICDATA']._serialized_start=119
  _globals['_DYNAMICDATA']._serialized_end=715
  _globals['_DYNAMICDATA_TYPE']._serialized_start=369
  _globals['_DYNAMICDATA_TYPE']._serialized_end=522
  _globals['_DYNAMICDATA_GEOTYPE']._serialized_start=524
  _globals['_DYNAMICDATA_GEOTYPE']._serialized_end=607
  _globals['_DYNAMICDATA_BELONGINGREGION']._serialized_start=609
  _globals['_DYNAMICDATA_BELONGINGREGION']._serialized_end=715
  _globals['_DYNAMIC']._serialized_start=718
  _globals['_DYNAMIC']._serialized_end=847
# @@protoc_insertion_point(module_scope)
