# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common_msgs/map_msgs/map_road.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'common_msgs/map_msgs/map_road.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common_msgs.map_msgs import map_geometry_pb2 as common__msgs_dot_map__msgs_dot_map__geometry__pb2
from common_msgs.map_msgs import map_id_pb2 as common__msgs_dot_map__msgs_dot_map__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#common_msgs/map_msgs/map_road.proto\x12\x10map_engine.hdmap\x1a\'common_msgs/map_msgs/map_geometry.proto\x1a!common_msgs/map_msgs/map_id.proto\"\xb1\x01\n\x0c\x42oundaryEdge\x12&\n\x05\x63urve\x18\x01 \x01(\x0b\x32\x17.map_engine.hdmap.Curve\x12\x31\n\x04type\x18\x02 \x01(\x0e\x32#.map_engine.hdmap.BoundaryEdge.Type\"F\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06NORMAL\x10\x01\x12\x11\n\rLEFT_BOUNDARY\x10\x02\x12\x12\n\x0eRIGHT_BOUNDARY\x10\x03\"?\n\x0f\x42oundaryPolygon\x12,\n\x04\x65\x64ge\x18\x01 \x03(\x0b\x32\x1e.map_engine.hdmap.BoundaryEdge\"y\n\x0cRoadBoundary\x12\x38\n\router_polygon\x18\x01 \x01(\x0b\x32!.map_engine.hdmap.BoundaryPolygon\x12/\n\x04hole\x18\x02 \x03(\x0b\x32!.map_engine.hdmap.BoundaryPolygon\"l\n\x0fRoadROIBoundary\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.map_engine.hdmap.Id\x12\x37\n\x0froad_boundaries\x18\x02 \x03(\x0b\x32\x1e.map_engine.hdmap.RoadBoundary\"\x88\x01\n\x0bRoadSection\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.map_engine.hdmap.Id\x12%\n\x07lane_id\x18\x02 \x03(\x0b\x32\x14.map_engine.hdmap.Id\x12\x30\n\x08\x62oundary\x18\x03 \x01(\x0b\x32\x1e.map_engine.hdmap.RoadBoundary\"\xe9\x01\n\x04Road\x12 \n\x02id\x18\x01 \x01(\x0b\x32\x14.map_engine.hdmap.Id\x12.\n\x07section\x18\x02 \x03(\x0b\x32\x1d.map_engine.hdmap.RoadSection\x12)\n\x0bjunction_id\x18\x03 \x01(\x0b\x32\x14.map_engine.hdmap.Id\x12)\n\x04type\x18\x04 \x01(\x0e\x32\x1b.map_engine.hdmap.Road.Type\"9\n\x04Type\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07HIGHWAY\x10\x01\x12\r\n\tCITY_ROAD\x10\x02\x12\x08\n\x04PARK\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_msgs.map_msgs.map_road_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOUNDARYEDGE']._serialized_start=134
  _globals['_BOUNDARYEDGE']._serialized_end=311
  _globals['_BOUNDARYEDGE_TYPE']._serialized_start=241
  _globals['_BOUNDARYEDGE_TYPE']._serialized_end=311
  _globals['_BOUNDARYPOLYGON']._serialized_start=313
  _globals['_BOUNDARYPOLYGON']._serialized_end=376
  _globals['_ROADBOUNDARY']._serialized_start=378
  _globals['_ROADBOUNDARY']._serialized_end=499
  _globals['_ROADROIBOUNDARY']._serialized_start=501
  _globals['_ROADROIBOUNDARY']._serialized_end=609
  _globals['_ROADSECTION']._serialized_start=612
  _globals['_ROADSECTION']._serialized_end=748
  _globals['_ROAD']._serialized_start=751
  _globals['_ROAD']._serialized_end=984
  _globals['_ROAD_TYPE']._serialized_start=927
  _globals['_ROAD_TYPE']._serialized_end=984
# @@protoc_insertion_point(module_scope)
