# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common_msgs/basic_msgs/drive_event.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'common_msgs/basic_msgs/drive_event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common_msgs.basic_msgs import header_pb2 as common__msgs_dot_basic__msgs_dot_header__pb2
from common_msgs.localization_msgs import pose_pb2 as common__msgs_dot_localization__msgs_dot_pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(common_msgs/basic_msgs/drive_event.proto\x12\x11map_engine.common\x1a#common_msgs/basic_msgs/header.proto\x1a(common_msgs/localization_msgs/pose.proto\"\x82\x02\n\nDriveEvent\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.map_engine.common.Header\x12\r\n\x05\x65vent\x18\x02 \x01(\t\x12/\n\x08location\x18\x03 \x01(\x0b\x32\x1d.map_engine.localization.Pose\x12\x30\n\x04type\x18\x04 \x03(\x0e\x32\".map_engine.common.DriveEvent.Type\x12\x15\n\ris_reportable\x18\x05 \x01(\x08\"@\n\x04Type\x12\x0c\n\x08\x43RITICAL\x10\x00\x12\x0b\n\x07PROBLEM\x10\x01\x12\x0b\n\x07\x44\x45SIRED\x10\x02\x12\x10\n\x0cOUT_OF_SCOPE\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_msgs.basic_msgs.drive_event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DRIVEEVENT']._serialized_start=143
  _globals['_DRIVEEVENT']._serialized_end=401
  _globals['_DRIVEEVENT_TYPE']._serialized_start=337
  _globals['_DRIVEEVENT_TYPE']._serialized_end=401
# @@protoc_insertion_point(module_scope)
